[build]
target = "index.html"
dist = "dist"

[[copy]]
source = "_headers"

[watch]
watch = ["src", "index.html"]

[serve]
address = "127.0.0.1"
port = 8080
open = true
headers = { "Cross-Origin-Opener-Policy" = "same-origin", "Cross-Origin-Embedder-Policy" = "require-corp" }
